apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ankitkubefio
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: ankitgdfio
    spec:
      containers:
      - name: fiocon
        image: ankitgd/fio_drv
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - mountPath: /mnt/v1
          name: fiokdeployvol
        args:
          ["--size=1G",
           "--name=test",
           "--readwrite=write",
           "--directory=/mnt/v1",
           "--ioengine=libaio",
           "--filename=file2.txt"]
      volumes:
      - name: fiokdeployvol
        persistentVolumeClaim:
          claimName: px-pvc-7
