apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-1
  namespace: prod-15
  annotations:
    volume.beta.kubernetes.io/storage-class: portworx-sc-repl3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
