##### Portworx persistent volume claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: name.snap001-source.px-fio-pvc-1
   annotations:
     volume.beta.kubernetes.io/storage-class: px-fio-sc-1 
spec:
   accessModes:
     - ReadWriteOnce
   resources:
      requests:
         storage: 100Gi
---
