##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-sc-2
provisioner: kubernetes.io/portworx-volume
parameters:
   fs: "ext4"
   block_size: "128k"
   repl: "2"
   shared: "true"
   label: "name=qa"
   aggregation_level: "1"
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-pvc-2
   annotations:
     volume.beta.kubernetes.io/storage-class: px-sc-2
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  # format is name.<new_snapshot_name>-source.<old_pvc_name>
  name: name.snap1-source.px-pvc-2
  annotations:
    volume.beta.kubernetes.io/storage-class: px-sc-2
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
---
