kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
   name: node-get-put-list-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["watch", "get", "update", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-sc-5
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "2"
   shared: "true"
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-pvc-5
   namespace: dev
   annotations:
     volume.beta.kubernetes.io/storage-class: px-sc-5
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: dev
  name: ns.dev-name.px-snap-1
  annotations:
    volume.beta.kubernetes.io/storage-class: px-sc-5
    px/snapshot-source-pvc: px-pvc-5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
