apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: ankitkubefio
spec:
  containers:
  - name: fiocon
    image: ankitgd/fio_drv
    volumeMounts:
    - mountPath: /mnt/v1
      name: fiokdeployvol
    args:
      ["--size=1G",
       "--name=test",
       "--readwrite=write",
       "--directory=/mnt/v1",
       "--ioengine=libaio",
       "--filename=file2.txt"]
  restartPolicy: Never 
  volumes:
  - name: fiokdeployvol
    persistentVolumeClaim:
      claimName: px-pvc-9
