##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-sc-4
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "2"
   shared: "true"
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-pvc-4
   namespace: default 
   annotations:
     volume.beta.kubernetes.io/storage-class: px-sc-4
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 4Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: default
  name: ns.default-name.px-snap-1
  annotations:
    volume.beta.kubernetes.io/storage-class: px-sc-4
    px/snapshot-source-pvc: px-pvc-4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: default
  name: ns.default-name.px-snap-2
  annotations:
    volume.beta.kubernetes.io/storage-class: px-sc-4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
