apiVersion: v1
kind: Namespace
metadata:
  name: prod 
  labels:
    name: prod
---
##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-sc-12
provisioner: kubernetes.io/portworx-volume
parameters:
   fs: "ext4"
   repl: "2"
   shared: "true"
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-pvc-12
   namespace: default
   annotations:
     volume.beta.kubernetes.io/storage-class: px-sc-12
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 12Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: prod
  name: ns.prod-name.px-snap-12
  annotations:
    volume.beta.kubernetes.io/storage-class: px-sc-12
    px/snapshot-source-pvc: px-pvc-12
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
---
